import { Boat, User, SwipeProfile, Conversation, Message, Booking } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'brennan@prestigeworldwide.com',
    full_name: 'Brennan Huff',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Brennan&backgroundColor=b6e3f4',
    bio: 'CEO of Prestige Worldwide. The first word in entertainment. I have a mangina.',
    is_boat_owner: true,
    looking_for: 'both',
    gender: 'male',
    age: 39,
    location: 'Los Angeles, CA',
    instagram_handle: '@prestigeworldwide',
    created_at: '2024-01-01',
  },
  {
    id: '2',
    email: 'dale@prestigeworldwide.com',
    full_name: 'Dale Doback',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Dale&backgroundColor=ffd5dc',
    bio: 'COO of Prestige Worldwide. I have a drum set. Do NOT touch it.',
    is_boat_owner: true,
    looking_for: 'both',
    gender: 'male',
    age: 40,
    location: 'Los Angeles, CA',
    instagram_handle: '@daledoback',
    created_at: '2024-01-01',
  },
  {
    id: '3',
    email: 'derek@boats.com',
    full_name: 'Derek Huff',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Derek&backgroundColor=c0aede',
    bio: 'Successful helicopter pilot. I can sing. No really, I can.',
    is_boat_owner: true,
    looking_for: 'dating',
    gender: 'male',
    age: 35,
    location: 'Santa Monica, CA',
    instagram_handle: '@derekhuff',
    created_at: '2024-02-15',
  },
  {
    id: '4',
    email: 'alice@yacht.com',
    full_name: 'Alice Waters',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Alice&backgroundColor=ffdfbf',
    bio: 'Love the ocean, love a good party. Looking for boat days and sunset vibes.',
    is_boat_owner: false,
    looking_for: 'boat_party',
    gender: 'female',
    age: 28,
    location: 'Miami, FL',
    instagram_handle: '@aliceonwater',
    created_at: '2024-03-01',
  },
  {
    id: '5',
    email: 'marina@sail.com',
    full_name: 'Marina Del Rey',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Marina&backgroundColor=d1f4d1',
    bio: 'Named after the harbor, destined for the sea. Champagne enthusiast.',
    is_boat_owner: false,
    looking_for: 'both',
    gender: 'female',
    age: 26,
    location: 'Marina Del Rey, CA',
    instagram_handle: '@marinadelrey',
    created_at: '2024-03-15',
  },
  {
    id: '6',
    email: 'captain@jack.com',
    full_name: 'Captain Jack',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Jack&backgroundColor=b6e3f4',
    bio: 'Why is the rum always gone? 15 years of sailing experience. Party animal.',
    is_boat_owner: true,
    looking_for: 'boat_party',
    gender: 'male',
    age: 45,
    location: 'Key West, FL',
    instagram_handle: '@captainjack',
    created_at: '2024-04-01',
  },
];

export const mockBoats: Boat[] = [
  {
    id: '1',
    owner_id: '1',
    owner: mockUsers[0],
    name: 'The Prestige',
    type: 'yacht',
    description: 'The crown jewel of Prestige Worldwide\'s fleet. 85ft of pure luxury. This is where we filmed the Boats N\' Hoes music video. Features a full bar, hot tub, and enough room for your entire Catalina Wine Mixer guest list.',
    hourly_rate: 750,
    capacity: 20,
    length_ft: 85,
    year: 2023,
    location: 'Marina Del Rey, CA',
    latitude: 33.9802,
    longitude: -118.4518,
    images: [
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800',
    ],
    amenities: ['Hot Tub', 'Full Bar', 'DJ Booth', 'Jet Skis', 'Karaoke Machine', 'Helicopter Pad'],
    is_available: true,
    rating: 4.9,
    review_count: 127,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    owner_id: '2',
    owner: mockUsers[1],
    name: 'Drum Solo',
    type: 'speedboat',
    description: 'Fast, loud, and impossible to ignore. Just like Dale\'s drum solos. This speedboat hits 65mph and has the sickest sound system on the water. POW!',
    hourly_rate: 350,
    capacity: 8,
    length_ft: 32,
    year: 2024,
    location: 'Long Beach, CA',
    latitude: 33.7701,
    longitude: -118.1937,
    images: [
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800',
      'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=800',
    ],
    amenities: ['Premium Sound System', 'Wakeboard Rack', 'Cooler', 'LED Lights'],
    is_available: true,
    rating: 4.7,
    review_count: 83,
    created_at: '2024-02-01',
  },
  {
    id: '3',
    owner_id: '3',
    owner: mockUsers[2],
    name: 'Catalina Dreamer',
    type: 'sailboat',
    description: 'Perfect for the Catalina Wine Mixer. Elegant 45ft sailing yacht with classic lines and a wine cellar below deck. The f***ing Catalina Wine Mixer.',
    hourly_rate: 450,
    capacity: 12,
    length_ft: 45,
    year: 2022,
    location: 'Catalina Island, CA',
    latitude: 33.3428,
    longitude: -118.3289,
    images: [
      'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=800',
      'https://images.unsplash.com/photo-1559034750-cdab70a66b8e?w=800',
    ],
    amenities: ['Wine Cellar', 'Sun Deck', 'Kayaks', 'Snorkeling Gear', 'BBQ Grill'],
    is_available: true,
    rating: 4.8,
    review_count: 56,
    created_at: '2024-02-15',
  },
  {
    id: '4',
    owner_id: '6',
    owner: mockUsers[5],
    name: 'Party Pontoon',
    type: 'pontoon',
    description: 'The ultimate floating party platform. Triple-decker pontoon with waterslide, diving board, and the most ridiculous LED light setup you\'ve ever seen. This boat has hosted more parties than your college dorm.',
    hourly_rate: 275,
    capacity: 25,
    length_ft: 30,
    year: 2024,
    location: 'Key West, FL',
    latitude: 24.5551,
    longitude: -81.7800,
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec40?w=800',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ],
    amenities: ['Waterslide', 'Diving Board', 'LED Party Lights', 'BBQ Grill', 'Bluetooth Speakers', 'Coolers'],
    is_available: true,
    rating: 4.6,
    review_count: 201,
    created_at: '2024-03-01',
  },
  {
    id: '5',
    owner_id: '6',
    owner: mockUsers[5],
    name: 'The Rum Runner',
    type: 'catamaran',
    description: 'A 55ft catamaran built for island hopping and rum drinking. Smooth ride, massive deck space, and a fully stocked tiki bar. Where the rum is never gone.',
    hourly_rate: 550,
    capacity: 16,
    length_ft: 55,
    year: 2023,
    location: 'Miami, FL',
    latitude: 25.7617,
    longitude: -80.1918,
    images: [
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800',
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
    ],
    amenities: ['Tiki Bar', 'Trampolines', 'Snorkeling Gear', 'Paddleboards', 'Hammocks', 'Underwater Lights'],
    is_available: true,
    rating: 4.9,
    review_count: 94,
    created_at: '2024-03-15',
  },
  {
    id: '6',
    owner_id: '1',
    owner: mockUsers[0],
    name: 'Night Ranger',
    type: 'yacht',
    description: 'Named after the greatest band ever. 65ft motor yacht with blacked-out exterior and neon interior. Perfect for nighttime cruises and making bad decisions.',
    hourly_rate: 650,
    capacity: 15,
    length_ft: 65,
    year: 2024,
    location: 'San Diego, CA',
    latitude: 32.7157,
    longitude: -117.1611,
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800',
    ],
    amenities: ['Neon Lighting', 'DJ Booth', 'Full Bar', 'Hot Tub', 'Drone Launch Pad', 'Fog Machine'],
    is_available: true,
    rating: 4.8,
    review_count: 68,
    created_at: '2024-04-01',
  },
];

export const mockSwipeProfiles: SwipeProfile[] = [
  {
    user: mockUsers[3],
    boat: mockBoats[0],
    distance_miles: 2.4,
    mutual_interests: ['Yacht Parties', 'Sunset Cruises', 'Champagne'],
  },
  {
    user: mockUsers[4],
    boat: undefined,
    distance_miles: 0.8,
    mutual_interests: ['Sailing', 'Wine Tasting', 'Beach Days'],
  },
  {
    user: mockUsers[0],
    boat: mockBoats[0],
    distance_miles: 5.1,
    mutual_interests: ['Karaoke', 'Entertainment', 'Prestige Worldwide'],
  },
  {
    user: mockUsers[1],
    boat: mockBoats[1],
    distance_miles: 3.7,
    mutual_interests: ['Drumming', 'Speed Boats', 'Bunk Beds'],
  },
  {
    user: mockUsers[5],
    boat: mockBoats[3],
    distance_miles: 12.3,
    mutual_interests: ['Rum', 'Island Hopping', 'Fishing'],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participant_ids: ['1', '4'],
    participants: [mockUsers[0], mockUsers[3]],
    last_message: {
      id: 'm1',
      conversation_id: '1',
      sender_id: '4',
      content: 'Is The Prestige available this Saturday? I\'ve got a group of 12!',
      is_ai: false,
      created_at: '2024-04-10T14:30:00Z',
    },
    booking_id: null,
    match_id: null,
    is_concierge: false,
    created_at: '2024-04-10T14:00:00Z',
    updated_at: '2024-04-10T14:30:00Z',
  },
  {
    id: '2',
    participant_ids: ['1'],
    last_message: {
      id: 'm2',
      conversation_id: '2',
      sender_id: 'ai',
      sender: undefined,
      content: 'Welcome to the Boats N\' Hoes AI Concierge! I can help you find the perfect boat, plan your trip, or answer any questions. What are you looking for today?',
      is_ai: true,
      created_at: '2024-04-10T10:00:00Z',
    },
    booking_id: null,
    match_id: null,
    is_concierge: true,
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2024-04-10T10:00:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    conversation_id: '2',
    sender_id: 'ai',
    content: 'Welcome to the Boats N\' Hoes AI Concierge! I\'m your personal boat butler, powered by Prestige Worldwide\'s cutting-edge AI. I can help you find the perfect vessel, plan epic boat days, or just chat about boats. What\'s on your mind, captain?',
    is_ai: true,
    created_at: '2024-04-10T10:00:00Z',
  },
  {
    id: 'm2',
    conversation_id: '2',
    sender_id: '1',
    content: 'I need a yacht for 15 people this weekend in Marina Del Rey. Budget is around $2000. What do you got?',
    is_ai: false,
    created_at: '2024-04-10T10:01:00Z',
  },
  {
    id: 'm3',
    conversation_id: '2',
    sender_id: 'ai',
    content: 'Great taste! For 15 people in Marina Del Rey, I\'d recommend **The Prestige** - an 85ft yacht at $750/hr. It\'s got a hot tub, full bar, DJ booth, and even a karaoke machine. For a 3-hour cruise, you\'re looking at $2,250. Want me to check availability for Saturday or Sunday?',
    is_ai: true,
    created_at: '2024-04-10T10:01:30Z',
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    boat_id: '1',
    boat: mockBoats[0],
    renter_id: '4',
    renter: mockUsers[3],
    start_time: '2024-04-15T10:00:00Z',
    end_time: '2024-04-15T14:00:00Z',
    total_price: 3000,
    status: 'confirmed',
    party_size: 12,
    special_requests: 'Need extra champagne and a Bluetooth speaker for karaoke',
    created_at: '2024-04-10T15:00:00Z',
  },
  {
    id: '2',
    boat_id: '3',
    boat: mockBoats[2],
    renter_id: '5',
    renter: mockUsers[4],
    start_time: '2024-04-20T16:00:00Z',
    end_time: '2024-04-20T20:00:00Z',
    total_price: 1800,
    status: 'pending',
    party_size: 8,
    special_requests: 'Catalina Wine Mixer theme please!',
    created_at: '2024-04-12T09:00:00Z',
  },
];
