import { Boat, User, SwipeProfile, Conversation, Message, Booking, AggregatedListing, BroProfile, Crew } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'brennan@prestigeworldwide.com',
    full_name: 'Brennan Huff',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Brennan&backgroundColor=b6e3f4',
    bio: 'CEO of Prestige Worldwide. The first word in entertainment. I have a mangina.',
    is_boat_owner: true,
    looking_for: 'both',
    gender: 'male',
    age: 39,
    location: 'Los Angeles, CA',
    instagram_handle: '@prestigeworldwide',
    created_at: '2024-01-01',
  },
  {
    id: '2',
    email: 'dale@prestigeworldwide.com',
    full_name: 'Dale Doback',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Dale&backgroundColor=ffd5dc',
    bio: 'COO of Prestige Worldwide. I have a drum set. Do NOT touch it.',
    is_boat_owner: true,
    looking_for: 'both',
    gender: 'male',
    age: 40,
    location: 'Los Angeles, CA',
    instagram_handle: '@daledoback',
    created_at: '2024-01-01',
  },
  {
    id: '3',
    email: 'derek@boats.com',
    full_name: 'Derek Huff',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Derek&backgroundColor=c0aede',
    bio: 'Successful helicopter pilot. I can sing. No really, I can.',
    is_boat_owner: true,
    looking_for: 'dating',
    gender: 'male',
    age: 35,
    location: 'Santa Monica, CA',
    instagram_handle: '@derekhuff',
    created_at: '2024-02-15',
  },
  {
    id: '4',
    email: 'alice@yacht.com',
    full_name: 'Alice Waters',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Alice&backgroundColor=ffdfbf',
    bio: 'Love the ocean, love a good party. Looking for boat days and sunset vibes.',
    is_boat_owner: false,
    looking_for: 'boat_party',
    gender: 'female',
    age: 28,
    location: 'Miami, FL',
    instagram_handle: '@aliceonwater',
    created_at: '2024-03-01',
  },
  {
    id: '5',
    email: 'marina@sail.com',
    full_name: 'Marina Del Rey',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Marina&backgroundColor=d1f4d1',
    bio: 'Named after the harbor, destined for the sea. Champagne enthusiast.',
    is_boat_owner: false,
    looking_for: 'both',
    gender: 'female',
    age: 26,
    location: 'Marina Del Rey, CA',
    instagram_handle: '@marinadelrey',
    created_at: '2024-03-15',
  },
  {
    id: '6',
    email: 'captain@jack.com',
    full_name: 'Captain Jack',
    avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Jack&backgroundColor=b6e3f4',
    bio: 'Why is the rum always gone? 15 years of sailing experience. Party animal.',
    is_boat_owner: true,
    looking_for: 'boat_party',
    gender: 'male',
    age: 45,
    location: 'Key West, FL',
    instagram_handle: '@captainjack',
    created_at: '2024-04-01',
  },
];

export const mockBoats: Boat[] = [
  {
    id: '1',
    owner_id: '1',
    owner: mockUsers[0],
    name: 'The Prestige',
    type: 'yacht',
    description: 'The crown jewel of Prestige Worldwide\'s fleet. 85ft of pure luxury. This is where we filmed the Boats N\' Hoes music video. Features a full bar, hot tub, and enough room for your entire Catalina Wine Mixer guest list.',
    hourly_rate: 750,
    capacity: 20,
    length_ft: 85,
    year: 2023,
    location: 'Marina Del Rey, CA',
    latitude: 33.9802,
    longitude: -118.4518,
    images: [
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800',
    ],
    amenities: ['Hot Tub', 'Full Bar', 'DJ Booth', 'Jet Skis', 'Karaoke Machine', 'Helicopter Pad'],
    is_available: true,
    rating: 4.9,
    review_count: 127,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    owner_id: '2',
    owner: mockUsers[1],
    name: 'Drum Solo',
    type: 'speedboat',
    description: 'Fast, loud, and impossible to ignore. Just like Dale\'s drum solos. This speedboat hits 65mph and has the sickest sound system on the water. POW!',
    hourly_rate: 350,
    capacity: 8,
    length_ft: 32,
    year: 2024,
    location: 'Long Beach, CA',
    latitude: 33.7701,
    longitude: -118.1937,
    images: [
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800',
      'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=800',
    ],
    amenities: ['Premium Sound System', 'Wakeboard Rack', 'Cooler', 'LED Lights'],
    is_available: true,
    rating: 4.7,
    review_count: 83,
    created_at: '2024-02-01',
  },
  {
    id: '3',
    owner_id: '3',
    owner: mockUsers[2],
    name: 'Catalina Dreamer',
    type: 'sailboat',
    description: 'Perfect for the Catalina Wine Mixer. Elegant 45ft sailing yacht with classic lines and a wine cellar below deck. The f***ing Catalina Wine Mixer.',
    hourly_rate: 450,
    capacity: 12,
    length_ft: 45,
    year: 2022,
    location: 'Catalina Island, CA',
    latitude: 33.3428,
    longitude: -118.3289,
    images: [
      'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=800',
      'https://images.unsplash.com/photo-1559034750-cdab70a66b8e?w=800',
    ],
    amenities: ['Wine Cellar', 'Sun Deck', 'Kayaks', 'Snorkeling Gear', 'BBQ Grill'],
    is_available: true,
    rating: 4.8,
    review_count: 56,
    created_at: '2024-02-15',
  },
  {
    id: '4',
    owner_id: '6',
    owner: mockUsers[5],
    name: 'Party Pontoon',
    type: 'pontoon',
    description: 'The ultimate floating party platform. Triple-decker pontoon with waterslide, diving board, and the most ridiculous LED light setup you\'ve ever seen. This boat has hosted more parties than your college dorm.',
    hourly_rate: 275,
    capacity: 25,
    length_ft: 30,
    year: 2024,
    location: 'Key West, FL',
    latitude: 24.5551,
    longitude: -81.7800,
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec40?w=800',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ],
    amenities: ['Waterslide', 'Diving Board', 'LED Party Lights', 'BBQ Grill', 'Bluetooth Speakers', 'Coolers'],
    is_available: true,
    rating: 4.6,
    review_count: 201,
    created_at: '2024-03-01',
  },
  {
    id: '5',
    owner_id: '6',
    owner: mockUsers[5],
    name: 'The Rum Runner',
    type: 'catamaran',
    description: 'A 55ft catamaran built for island hopping and rum drinking. Smooth ride, massive deck space, and a fully stocked tiki bar. Where the rum is never gone.',
    hourly_rate: 550,
    capacity: 16,
    length_ft: 55,
    year: 2023,
    location: 'Miami, FL',
    latitude: 25.7617,
    longitude: -80.1918,
    images: [
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800',
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
    ],
    amenities: ['Tiki Bar', 'Trampolines', 'Snorkeling Gear', 'Paddleboards', 'Hammocks', 'Underwater Lights'],
    is_available: true,
    rating: 4.9,
    review_count: 94,
    created_at: '2024-03-15',
  },
  {
    id: '6',
    owner_id: '1',
    owner: mockUsers[0],
    name: 'Night Ranger',
    type: 'yacht',
    description: 'Named after the greatest band ever. 65ft motor yacht with blacked-out exterior and neon interior. Perfect for nighttime cruises and making bad decisions.',
    hourly_rate: 650,
    capacity: 15,
    length_ft: 65,
    year: 2024,
    location: 'San Diego, CA',
    latitude: 32.7157,
    longitude: -117.1611,
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800',
    ],
    amenities: ['Neon Lighting', 'DJ Booth', 'Full Bar', 'Hot Tub', 'Drone Launch Pad', 'Fog Machine'],
    is_available: true,
    rating: 4.8,
    review_count: 68,
    created_at: '2024-04-01',
  },
];

export const mockSwipeProfiles: SwipeProfile[] = [
  {
    user: mockUsers[3],
    boat: mockBoats[0],
    distance_miles: 2.4,
    mutual_interests: ['Yacht Parties', 'Sunset Cruises', 'Champagne'],
  },
  {
    user: mockUsers[4],
    boat: undefined,
    distance_miles: 0.8,
    mutual_interests: ['Sailing', 'Wine Tasting', 'Beach Days'],
  },
  {
    user: mockUsers[0],
    boat: mockBoats[0],
    distance_miles: 5.1,
    mutual_interests: ['Karaoke', 'Entertainment', 'Prestige Worldwide'],
  },
  {
    user: mockUsers[1],
    boat: mockBoats[1],
    distance_miles: 3.7,
    mutual_interests: ['Drumming', 'Speed Boats', 'Bunk Beds'],
  },
  {
    user: mockUsers[5],
    boat: mockBoats[3],
    distance_miles: 12.3,
    mutual_interests: ['Rum', 'Island Hopping', 'Fishing'],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participant_ids: ['1', '4'],
    participants: [mockUsers[0], mockUsers[3]],
    last_message: {
      id: 'm1',
      conversation_id: '1',
      sender_id: '4',
      content: 'Is The Prestige available this Saturday? I\'ve got a group of 12!',
      is_ai: false,
      created_at: '2024-04-10T14:30:00Z',
    },
    booking_id: null,
    match_id: null,
    is_concierge: false,
    created_at: '2024-04-10T14:00:00Z',
    updated_at: '2024-04-10T14:30:00Z',
  },
  {
    id: '2',
    participant_ids: ['1'],
    last_message: {
      id: 'm2',
      conversation_id: '2',
      sender_id: 'ai',
      sender: undefined,
      content: 'Welcome to the Boats N\' Hoes AI Concierge! I can help you find the perfect boat, plan your trip, or answer any questions. What are you looking for today?',
      is_ai: true,
      created_at: '2024-04-10T10:00:00Z',
    },
    booking_id: null,
    match_id: null,
    is_concierge: true,
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2024-04-10T10:00:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    conversation_id: '2',
    sender_id: 'ai',
    content: 'Welcome to the Boats N\' Hoes AI Concierge! I\'m your personal boat butler, powered by Prestige Worldwide\'s cutting-edge AI. I can help you find the perfect vessel, plan epic boat days, or just chat about boats. What\'s on your mind, captain?',
    is_ai: true,
    created_at: '2024-04-10T10:00:00Z',
  },
  {
    id: 'm2',
    conversation_id: '2',
    sender_id: '1',
    content: 'I need a yacht for 15 people this weekend in Marina Del Rey. Budget is around $2000. What do you got?',
    is_ai: false,
    created_at: '2024-04-10T10:01:00Z',
  },
  {
    id: 'm3',
    conversation_id: '2',
    sender_id: 'ai',
    content: 'Great taste! For 15 people in Marina Del Rey, I\'d recommend **The Prestige** - an 85ft yacht at $750/hr. It\'s got a hot tub, full bar, DJ booth, and even a karaoke machine. For a 3-hour cruise, you\'re looking at $2,250. Want me to check availability for Saturday or Sunday?',
    is_ai: true,
    created_at: '2024-04-10T10:01:30Z',
  },
];

// ─── BOATS N' BROS ───────────────────────────────────────

export const mockBroProfiles: BroProfile[] = [
  {
    user: mockUsers[0],
    vibe: 'party',
    boat_preferences: ['Yacht', 'Catamaran', 'Pontoon'],
    availability: 'Weekends',
    crew_size_preferred: 8,
    fun_fact: 'Once karaoked for 6 hours straight on a moving yacht',
    distance_miles: 1.2,
    mutual_interests: ['Yacht Parties', 'Karaoke', 'Prestige Worldwide'],
  },
  {
    user: mockUsers[1],
    vibe: 'party',
    boat_preferences: ['Speedboat', 'Pontoon'],
    availability: 'Anytime',
    crew_size_preferred: 6,
    fun_fact: 'Can play drums on any surface including a boat hull',
    distance_miles: 1.5,
    mutual_interests: ['Wakeboarding', 'Music', 'Bunk Beds'],
  },
  {
    user: mockUsers[5],
    vibe: 'adventure',
    boat_preferences: ['Catamaran', 'Sailboat', 'Fishing'],
    availability: 'Weekdays & Weekends',
    crew_size_preferred: 10,
    fun_fact: '15 years of sailing and the rum is never gone on my watch',
    distance_miles: 8.3,
    mutual_interests: ['Deep Sea Fishing', 'Island Hopping', 'Rum Tasting'],
  },
  {
    user: {
      id: '7',
      email: 'chad@boatlife.com',
      full_name: 'Chad Waverly',
      avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Chad&backgroundColor=c0aede',
      bio: 'Bro, do you even boat? Ex-college rower turned yacht enthusiast. Will bring the cooler.',
      is_boat_owner: false,
      looking_for: 'boat_party',
      gender: 'male',
      age: 31,
      location: 'Newport Beach, CA',
      instagram_handle: '@chadwaverly',
      created_at: '2024-05-01',
    },
    vibe: 'watersports',
    boat_preferences: ['Speedboat', 'Yacht'],
    availability: 'Weekends',
    crew_size_preferred: 8,
    fun_fact: 'Can waterski on one leg while holding a beer',
    distance_miles: 4.7,
    mutual_interests: ['Wakeboarding', 'Jet Skiing', 'Beach Volleyball'],
  },
  {
    user: {
      id: '8',
      email: 'tony@fishon.com',
      full_name: 'Tony Marlin',
      avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Tony&backgroundColor=ffd5dc',
      bio: 'If it swims, I can catch it. Looking for fishing bros who appreciate a 5am wake-up call.',
      is_boat_owner: true,
      looking_for: 'boat_party',
      gender: 'male',
      age: 38,
      location: 'San Diego, CA',
      instagram_handle: '@tonymarlin',
      created_at: '2024-05-15',
    },
    vibe: 'fishing',
    boat_preferences: ['Fishing', 'Center Console'],
    availability: 'Early Mornings & Weekends',
    crew_size_preferred: 4,
    fun_fact: 'Caught a 200lb yellowfin tuna in a kayak once',
    distance_miles: 6.1,
    mutual_interests: ['Deep Sea Fishing', 'Spearfishing', 'Sushi Making'],
  },
  {
    user: {
      id: '9',
      email: 'mike@chillvibes.com',
      full_name: 'Mike Sunset',
      avatar_url: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Mike&backgroundColor=d1f4d1',
      bio: 'Sunset cruises and acoustic guitar on the water. Looking for mellow crew only.',
      is_boat_owner: false,
      looking_for: 'boat_party',
      gender: 'male',
      age: 34,
      location: 'Malibu, CA',
      instagram_handle: '@mikesunset',
      created_at: '2024-06-01',
    },
    vibe: 'chill',
    boat_preferences: ['Sailboat', 'Catamaran'],
    availability: 'Evenings & Weekends',
    crew_size_preferred: 6,
    fun_fact: 'Has watched every sunset from a boat for the last 3 years',
    distance_miles: 3.2,
    mutual_interests: ['Sunset Cruises', 'Acoustic Music', 'Wine'],
  },
];

export const mockCrews: Crew[] = [
  {
    id: 'crew-1',
    name: 'Prestige Worldwide Crew',
    captain_id: '1',
    captain: mockUsers[0],
    members: [mockUsers[0], mockUsers[1]],
    max_size: 8,
    vibe: 'party',
    description: 'The original party crew. Boats, hoes, and everything in between. POW!',
    next_trip: 'Catalina Wine Mixer - March 15',
    avatar_url: 'https://api.dicebear.com/9.x/shapes/svg?seed=PrestigeCrew&backgroundColor=D4AF37',
    created_at: '2024-01-01',
  },
  {
    id: 'crew-2',
    name: 'Dawn Patrol Anglers',
    captain_id: '8',
    members: [mockBroProfiles[4].user],
    max_size: 6,
    vibe: 'fishing',
    description: 'Early risers who live for the tug on the line. Tight lines, cold beers.',
    next_trip: 'Yellowfin Run - San Diego - March 20',
    avatar_url: 'https://api.dicebear.com/9.x/shapes/svg?seed=DawnPatrol&backgroundColor=00D4FF',
    created_at: '2024-02-15',
  },
  {
    id: 'crew-3',
    name: 'Sunset Sailors',
    captain_id: '9',
    members: [mockBroProfiles[5].user],
    max_size: 6,
    vibe: 'chill',
    description: 'Golden hour on the water. Acoustic vibes, good wine, great company.',
    avatar_url: 'https://api.dicebear.com/9.x/shapes/svg?seed=SunsetSailors&backgroundColor=FF6B35',
    created_at: '2024-03-01',
  },
];

// ─── AGGREGATED LISTINGS (from Boatsetter, GetMyBoat, etc.) ─

export const mockAggregatedListings: AggregatedListing[] = [
  {
    id: 'agg-1',
    source: 'boatsetter',
    external_url: 'https://www.boatsetter.com/boats/luxury-yacht-marina-del-rey',
    name: 'Sea Breeze 80ft Luxury Motor Yacht',
    type: 'yacht',
    description: 'Stunning 80ft motor yacht with 4 staterooms, full galley kitchen, flybridge with jacuzzi, and state-of-the-art entertainment system. Perfect for corporate events or milestone celebrations.',
    price_per_hour: 850,
    price_per_day: 6500,
    currency: 'USD',
    capacity: 25,
    length_ft: 80,
    year: 2022,
    location: 'Marina Del Rey, CA',
    city: 'Marina Del Rey',
    state: 'CA',
    images: [
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    ],
    amenities: ['Jacuzzi', 'Full Kitchen', 'Flybridge', 'Entertainment System', 'Jet Ski', 'Paddleboards'],
    captain_included: true,
    instant_book: false,
    rating: 4.9,
    review_count: 87,
    owner_name: 'Pacific Luxury Charters',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=PLC',
    owner_response_rate: 98,
    owner_response_time: 'Within 1 hour',
    cancellation_policy: 'moderate',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-2',
    source: 'getmyboat',
    external_url: 'https://www.getmyboat.com/boat-rentals/miami-party-catamaran',
    name: 'Island Time 50ft Party Catamaran',
    type: 'catamaran',
    description: 'The ultimate party platform on the water! Spacious 50ft catamaran with huge deck space, tiki bar, premium sound system, and trampolines on the bow nets. Your floating nightclub in Biscayne Bay.',
    price_per_hour: 650,
    price_per_day: 4800,
    currency: 'USD',
    capacity: 20,
    length_ft: 50,
    year: 2023,
    location: 'Miami, FL',
    city: 'Miami',
    state: 'FL',
    images: [
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80',
      'https://images.unsplash.com/photo-1559034750-cdab70a66b8e?w=800&q=80',
    ],
    amenities: ['Tiki Bar', 'Premium Sound', 'Trampolines', 'Snorkeling Gear', 'LED Lighting', 'BBQ Grill'],
    captain_included: true,
    instant_book: true,
    rating: 4.8,
    review_count: 143,
    owner_name: 'Miami Wave Charters',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=MWC',
    owner_response_rate: 95,
    owner_response_time: 'Within 2 hours',
    cancellation_policy: 'flexible',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-3',
    source: 'boatsetter',
    external_url: 'https://www.boatsetter.com/boats/key-west-fishing-charter',
    name: 'Reel Deal 36ft Center Console',
    type: 'center_console',
    description: 'Tournament-ready 36ft center console with triple 300HP outboards, top-of-the-line electronics, fighting chair, and live wells. Captain and mate included for an unforgettable fishing experience.',
    price_per_hour: 400,
    price_per_day: 2800,
    currency: 'USD',
    capacity: 8,
    length_ft: 36,
    year: 2024,
    location: 'Key West, FL',
    city: 'Key West',
    state: 'FL',
    images: [
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80',
      'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=800&q=80',
    ],
    amenities: ['Fighting Chair', 'Live Wells', 'Fish Finder', 'Rod Holders', 'Shade Top', 'Cooler'],
    captain_included: true,
    instant_book: false,
    rating: 4.9,
    review_count: 201,
    owner_name: 'Capt. Billy Bones',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=CBB',
    owner_response_rate: 100,
    owner_response_time: 'Within 30 minutes',
    cancellation_policy: 'strict',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-4',
    source: 'getmyboat',
    external_url: 'https://www.getmyboat.com/boat-rentals/san-diego-sunset-sail',
    name: 'Golden Hour 42ft Sailing Yacht',
    type: 'sailboat',
    description: 'Elegant 42ft sailing yacht perfect for romantic sunset cruises or intimate gatherings. Teak decks, spacious cockpit, and a below-deck salon with full galley. Wine and cheese packages available.',
    price_per_hour: 375,
    price_per_day: 2500,
    currency: 'USD',
    capacity: 10,
    length_ft: 42,
    year: 2021,
    location: 'San Diego, CA',
    city: 'San Diego',
    state: 'CA',
    images: [
      'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=800&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    ],
    amenities: ['Wine Cooler', 'Bluetooth Speakers', 'Sun Deck', 'Full Galley', 'Kayak', 'Snorkeling'],
    captain_included: true,
    instant_book: true,
    rating: 4.7,
    review_count: 68,
    owner_name: 'SoCal Sailing Co.',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=SSC',
    owner_response_rate: 92,
    owner_response_time: 'Within 3 hours',
    cancellation_policy: 'moderate',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-5',
    source: 'click_and_boat',
    external_url: 'https://www.clickandboat.com/boat-rental/newport-speedboat',
    name: 'Thunder 32ft Performance Speedboat',
    type: 'speedboat',
    description: 'High-performance 32ft speedboat with twin turbo engines reaching 65mph. Wake tower, premium JL Audio system, and seating for 10. Perfect for wakeboarding, tubing, or just ripping across the harbor.',
    price_per_hour: 450,
    price_per_day: 3200,
    currency: 'USD',
    capacity: 10,
    length_ft: 32,
    year: 2024,
    location: 'Newport Beach, CA',
    city: 'Newport Beach',
    state: 'CA',
    images: [
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    ],
    amenities: ['Wake Tower', 'Premium Audio', 'Wakeboard Rack', 'Tube', 'Cooler', 'Bimini Top'],
    captain_included: false,
    instant_book: true,
    rating: 4.6,
    review_count: 52,
    owner_name: 'Harbor Speed Rentals',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=HSR',
    owner_response_rate: 88,
    owner_response_time: 'Within 4 hours',
    cancellation_policy: 'flexible',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-6',
    source: 'sailo',
    external_url: 'https://www.sailo.com/yacht-charter/hamptons-mega-yacht',
    name: 'Olympus 120ft Mega Yacht',
    type: 'yacht',
    description: 'The pinnacle of maritime luxury. 120ft mega yacht with 5 staterooms, cinema room, infinity-edge jacuzzi, gym, and helipad. Full crew of 8 included. This is how legends vacation.',
    price_per_hour: 2500,
    price_per_day: 18000,
    currency: 'USD',
    capacity: 30,
    length_ft: 120,
    year: 2023,
    location: 'The Hamptons, NY',
    city: 'Sag Harbor',
    state: 'NY',
    images: [
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80',
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80',
    ],
    amenities: ['Helipad', 'Cinema Room', 'Infinity Jacuzzi', 'Gym', 'Jet Skis x4', 'Full Crew', 'Wine Cellar', 'Water Slide'],
    captain_included: true,
    instant_book: false,
    rating: 5.0,
    review_count: 23,
    owner_name: 'Atlantic Elite Yachts',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=AEY',
    owner_response_rate: 100,
    owner_response_time: 'Within 1 hour',
    cancellation_policy: 'strict',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-7',
    source: 'getmyboat',
    external_url: 'https://www.getmyboat.com/boat-rentals/lake-tahoe-pontoon',
    name: 'Lake Life 28ft Luxury Pontoon',
    type: 'pontoon',
    description: 'Premium tri-toon with plush seating, built-in coolers, bluetooth speakers, and a water slide off the back. The ultimate floating living room for Lake Tahoe cruises.',
    price_per_hour: 225,
    price_per_day: 1500,
    currency: 'USD',
    capacity: 14,
    length_ft: 28,
    year: 2024,
    location: 'Lake Tahoe, CA',
    city: 'South Lake Tahoe',
    state: 'CA',
    images: [
      'https://images.unsplash.com/photo-1514649923863-ceaf75b7ec40?w=800&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    ],
    amenities: ['Water Slide', 'Bluetooth Speakers', 'Built-in Coolers', 'Bimini Top', 'Swim Ladder', 'USB Charging'],
    captain_included: false,
    instant_book: true,
    rating: 4.8,
    review_count: 112,
    owner_name: 'Tahoe Boat Guys',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=TBG',
    owner_response_rate: 94,
    owner_response_time: 'Within 2 hours',
    cancellation_policy: 'flexible',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-8',
    source: 'boatsetter',
    external_url: 'https://www.boatsetter.com/boats/chicago-party-yacht',
    name: 'Windy City 65ft Entertainment Yacht',
    type: 'yacht',
    description: 'Chicago\'s premier party yacht! LED-lit dance floor, professional DJ booth, full commercial bar, and stunning views of the skyline from the upper deck. Corporate events and private parties welcome.',
    price_per_hour: 750,
    price_per_day: 5500,
    currency: 'USD',
    capacity: 40,
    length_ft: 65,
    year: 2022,
    location: 'Chicago, IL',
    city: 'Chicago',
    state: 'IL',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
      'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80',
    ],
    amenities: ['LED Dance Floor', 'DJ Booth', 'Commercial Bar', 'Upper Deck', 'Fog Machine', 'Photo Booth'],
    captain_included: true,
    instant_book: false,
    rating: 4.7,
    review_count: 176,
    owner_name: 'Chi-Town Yacht Club',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=CYC',
    owner_response_rate: 96,
    owner_response_time: 'Within 1 hour',
    cancellation_policy: 'moderate',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-9',
    source: 'getmyboat',
    external_url: 'https://www.getmyboat.com/boat-rentals/jet-ski-miami',
    name: 'Yamaha WaveRunner VX Cruiser',
    type: 'jet_ski',
    description: 'Brand new 2024 Yamaha WaveRunner! Perfect for blasting across Biscayne Bay. No experience needed - quick orientation included. Rent 1 or up to 6 for your whole crew.',
    price_per_hour: 95,
    price_per_day: 450,
    currency: 'USD',
    capacity: 2,
    length_ft: 11,
    year: 2024,
    location: 'Miami Beach, FL',
    city: 'Miami Beach',
    state: 'FL',
    images: [
      'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=800&q=80',
    ],
    amenities: ['Life Jacket', 'Orientation Included', 'GoPro Mount'],
    captain_included: false,
    instant_book: true,
    rating: 4.5,
    review_count: 312,
    owner_name: 'Miami Jet Ski Pros',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=MJP',
    owner_response_rate: 99,
    owner_response_time: 'Within 15 minutes',
    cancellation_policy: 'flexible',
    fetched_at: '2026-02-06T10:00:00Z',
  },
  {
    id: 'agg-10',
    source: 'click_and_boat',
    external_url: 'https://www.clickandboat.com/boat-rental/catalina-island-charter',
    name: 'Pacific Dream 55ft Luxury Catamaran',
    type: 'catamaran',
    description: 'Sail to Catalina Island in style aboard this magnificent 55ft catamaran. Two trampolines, full bar, gourmet kitchen, and 3 private cabins. Wine tasting packages available for the f***ing Catalina Wine Mixer.',
    price_per_hour: 700,
    price_per_day: 5000,
    currency: 'USD',
    capacity: 18,
    length_ft: 55,
    year: 2023,
    location: 'Catalina Island, CA',
    city: 'Avalon',
    state: 'CA',
    images: [
      'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=800&q=80',
      'https://images.unsplash.com/photo-1559034750-cdab70a66b8e?w=800&q=80',
    ],
    amenities: ['Wine Cellar', 'Trampolines', 'Full Bar', 'Kayaks x4', 'Snorkeling Gear', 'Paddleboards', 'BBQ'],
    captain_included: true,
    instant_book: false,
    rating: 4.9,
    review_count: 89,
    owner_name: 'Catalina Charter Co.',
    owner_avatar: 'https://api.dicebear.com/9.x/shapes/svg?seed=CCC',
    owner_response_rate: 97,
    owner_response_time: 'Within 1 hour',
    cancellation_policy: 'moderate',
    fetched_at: '2026-02-06T10:00:00Z',
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    boat_id: '1',
    boat: mockBoats[0],
    renter_id: '4',
    renter: mockUsers[3],
    start_time: '2024-04-15T10:00:00Z',
    end_time: '2024-04-15T14:00:00Z',
    total_price: 3000,
    status: 'confirmed',
    party_size: 12,
    special_requests: 'Need extra champagne and a Bluetooth speaker for karaoke',
    created_at: '2024-04-10T15:00:00Z',
  },
  {
    id: '2',
    boat_id: '3',
    boat: mockBoats[2],
    renter_id: '5',
    renter: mockUsers[4],
    start_time: '2024-04-20T16:00:00Z',
    end_time: '2024-04-20T20:00:00Z',
    total_price: 1800,
    status: 'pending',
    party_size: 8,
    special_requests: 'Catalina Wine Mixer theme please!',
    created_at: '2024-04-12T09:00:00Z',
  },
];
